console.log(
    [
        ["any"],
        ['"abc"'],
        ["5 of any"],
        ["many of any"],
        ["maybe any"],
        ["1 to 5 of any"],
        ["maybe 5 of any"],
        ["0 to many of any"],
        ['either "a" or "b"'],
        ['either "a" or "b" or "c"'],
        ["any of a, b, c"],
        ["any of a to c, x to z"],
        ["any of a, b, c, x to z"],
        ['"abc" # this is a comment'],
        ['\n"abc"'],
        ['\n"abc"\n\n'],
        ['"abc"\n'],
        ['any\nmaybe "hello"\nmany of any'],
        ["maybe\nany\nend"],
        ["many of\nany\nend"],
        ["3 of\nany\nend"],
        ["3 to 5 of\nany\nend"],
        ["maybe\nany\nmaybe any\nend"],
        ["maybe\nany\nmaybe any\nmany of any\nend"],
        ['begin group_name\n"abc"\nend'],
        ['either\n"a"\nor\n"b"\nend'],
        ['either\n"a"\nor\n"b"\nor\n"c"\nend'],
        ['define foo\n"bar"\nend\n"nothing"'],
        ['define foo\n"foo"\nend\nfoo'],
        ['define foo "foo"\nfoo'], // online variable definition
        ["any of\na, b\nc\nend"],
        ["any of\na to c\nx to z\nend"],
        ["any of\na\nb\nc\nx to z\nend"],
        ['# this is a comment\n"abc"'],
        ['# this is a comment\n# this is another\n"abc"\n# and another'],
    ].join("\n")
)
