
grammar DSL
    expression <- any                                       
                    / many_of
                    / maybe _ expression 
                    / number _ of _ expression              %count_of
                    / number _ to _ number _ of _ expression

    any <- "any"       %any
    many_of <- many _ of _ expression %many_of
    many <- "many"    
    of <- "of"
    maybe <-  "maybe"

    number <- [0-9]+

    _ <- [ \t]*
