
grammar DSL
    expression <- many _ of _ expression %many_of
                    / maybe  _ expression  %maybe
                    / number _ of _ expression              %count_of
                    / number _ to _ number _ of _ expression %count_range_of
                    / any

    any <- "any"       %any
    
    many <- "many"
    of <- "of"
    to <- "to"
    maybe <- "maybe"

    number <- [0-9]+

    _ <- [ \t]+
